apiVersion: v1
kind: Service
metadata:
  name: kanchi
  namespace: {{YOUR_K8S_NAMESPACE}}
spec:
  selector:
    app: kanchi
  ports:
    - name: api
      port: 8765
      targetPort: 8765
  type: ClusterIP
